Brother\ContactUsBundle\Entity\Entry:
    type: entity
    table: brother_contact_us
    indexes:
        created_at_idx:
            columns:
                - created_at
        name_idx:
            columns:
                - name
    id:
        id:
            type: bigint
            
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
        email:
            type: string
            nullable: false
        phone:
            type: string
            nullable: true
        message:
            type: text
            nullable: false
        created_at:
            type: datetime
            nullable: true
            column: created_at
        updated_at:
            type: datetime
            nullable: false
            column: updated_at
        deleted_at:
            type: datetime
            nullable: true
            column: deleted_at
    lifecycleCallbacks: {  }
