parameters:
    brother_contact_us.model.entry.class: Brother\ContactUsBundle\Entity\Entry
    brother_contact_us.manager.entry.class: Brother\ContactUsBundle\Entity\EntryManager
services:
    brother_contact_us.entity_manager:
        alias: 'doctrine.orm.entity_manager'

    brother_contact_us.entry_manager:
        class: %brother_contact_us.manager.entry.class%
        arguments:
            - '@event_dispatcher'
            - '@brother_contact_us.entity_manager'
            - %brother_contact_us.model.entry.class%
