services:
    brother_contact_us.admin.entry:
        class: Brother\ContactUsBundle\Admin\EntryAdmin
        arguments: [~, Brother\ContactUsBundle\Entity\Entry, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ContactUs}
