Brother\ContactUsBundle\Entity  \Entry:
    properties:
        name:
            - NotBlank:
                message: brother_contact_us.name.blank
            - Length:
                min: 3
                max: 255
                minMessage: brother_contact_us.name.short
                maxMessage: brother_contact_us.name.long

        email:
            - NotBlank:
                message: brother_contact_us.email.blank
            - Email:
                message: brother_contact_us.email.invalid
            - Length:
#                max: 100
                max: 255
                minMessage: brother_contact_us.email.short
                maxMessage: brother_contact_us.email.long

        message:
            - NotBlank:
                message: brother_contact_us.comment.blank
            - Length:
                min: 2
                #max: 255
                minMessage: brother_contact_us.comment.short
                maxMessage: brother_contact_us.comment.long
